AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "**/vendor/**/*"
    - "node_modules/**/*"
    - "**/node_modules/**/*"

Metrics/AbcSize:
  Max: 50

Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 200

Style/Documentation:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10
