AllCops:
  NewCops: enable

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    
Metrics/AbcSize:
  Max: 50

Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 200

Style/Documentation:
  Enabled: false
